FROM ubuntu:14.04
MAINTAINER Michael Merickel <michael@merickel.org>

RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get -yq install python2.7 python-pip python-virtualenv && apt-get clean

RUN pip install -q 'devpi=={{ DEVPI_VERSION }}'

VOLUME /data
EXPOSE 3141
ENTRYPOINT ["devpi-server", "--serverdir=/data", "--host=0.0.0.0"]
