FROM python:2.7
MAINTAINER Michael Merickel <michael@merickel.org>

RUN pip install -q 'devpi-server=={{ DEVPI_VERSION }}' devpi-web devpi-client

VOLUME /data
EXPOSE 3141
ENTRYPOINT ["devpi-server", "--serverdir=/data", "--host=0.0.0.0"]
